backend:
  name: zx772
  repo: zx772/my-blog
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章列表"
    folder: "content/posts"
    create: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "内容", name: "body", widget: "markdown" }